services:
  joplin:
    image: joplin/server:latest
    container_name: joplin
    restart: unless-stopped
    depends_on:
      - joplin_db
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_HOST=joplin_db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - basestation_net

  joplin_db:
    image: postgres:16
    container_name: joplin_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=joplin
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - joplin_db_data:/var/lib/postgresql/data
    networks:
      - basestation_net

volumes:
  joplin_db_data:

networks:
  basestation_net:
    external: true