services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://vaultwarden.mattmiranda.dev
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - ROCKET_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - vaultwarden_data:/data
    networks:
      - basestation_net
volumes:
  vaultwarden_data: null
networks:
  basestation_net:
    external: true
